name: pr test 🚀🚀🚀

on:
  pull_request:
    types: [synchronize, labeled]

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
        name: checkout with ref
      - name: cat a.out
        run: |
          git show HEAD
          git ls-files
          cat a.out
